# Stage 1 - Build the app
FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install --only=production

COPY . .

RUN npm run build

# Stage 2 - Serve the app
FROM node:18-alpine

WORKDIR /app

COPY --from=build /app /app

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
